### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by XianNvyu** [kashif/pytorch-transformer-ts#26]
when I try to debug lag-llama/train.py, this error occured.

Traceback (most recent call last):
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/numpy/core/getlimits.py", line 670, in __init__
    self.dtype = numeric.dtype(int_type)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/xly/code/pytorch-transformer-ts/lag-llama/estimator.py", line 17, in <module>
    from gluonts.torch.modules.loss import DistributionLoss, NegativeLogLikelihood
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/gluonts/torch/__init__.py", line 29, in <module>
    from .model.deep_npts import DeepNPTSEstimator
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/gluonts/torch/model/deep_npts/__init__.py", line 14, in <module>
    from ._estimator import DeepNPTSEstimator
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/gluonts/torch/model/deep_npts/_estimator.py", line 46, in <module>
    from ._network import (
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/gluonts/torch/model/deep_npts/_network.py", line 26, in <module>
    from gluonts.torch.distributions import DiscreteDistribution
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/gluonts/torch/distributions/__init__.py", line 31, in <module>
    from .negative_binomial import NegativeBinomialOutput
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/gluonts/torch/distributions/negative_binomial.py", line 22, in <module>
    from scipy.stats import nbinom
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/stats/__init__.py", line 608, in <module>
    from ._stats_py import *
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 39, in <module>
    from scipy.spatial.distance import cdist
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/spatial/__init__.py", line 110, in <module>
    from ._kdtree import *
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/spatial/_kdtree.py", line 4, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
  File "_ckdtree.pyx", line 12, in init scipy.spatial._ckdtree
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/sparse/__init__.py", line 287, in <module>
    from . import csgraph
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/sparse/csgraph/__init__.py", line 185, in <module>
    from ._laplacian import laplacian
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/sparse/linalg/__init__.py", line 120, in <module>
    from ._isolve import *
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/__init__.py", line 6, in <module>
    from .lgmres import lgmres
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/lgmres.py", line 7, in <module>
    from scipy.linalg import get_blas_funcs
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/linalg/__init__.py", line 206, in <module>
    from ._misc import *
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/linalg/_misc.py", line 4, in <module>
    from .lapack import get_lapack_funcs
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/scipy/linalg/lapack.py", line 975, in <module>
    _int32_max = _np.iinfo(_np.int32).max
  File "/home/xly/anaconda3/envs/c118p310/lib/python3.10/site-packages/numpy/core/getlimits.py", line 672, in __init__
    self.dtype = numeric.dtype(type(int_type))
TypeError: 'NoneType' object is not callable

**Comment by kashif** [comment]
can you try to upgrade your `scipy` version?
